[project]
name = "django-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1",
    "money>=1.3.0",
    "setuptools>=74.0.0",
]
